service: analytics

plugins:
  - serverless-google-cloudfunctions
  - serverless-remove-forced-login

provider:
  name: google
  runtime: nodejs
  project: ${file(./config.json):PROJECT_ID}
  credentials: ~/.gcloud/keyfile.json
  environment:
    CREDENTIALS_FILE: ${file(./config.json):CREDENTIALS_FILE}
    PROJECT_ID: ${file(./config.json):PROJECT_ID}
    DATASET_ID: ${file(./config.json):DATASET_ID}
    TABLE_ID: ${file(./config.json):TABLE_ID}

functions:
  analytics:
    handler: recordEvents
    events:
      - user.registered
      - user.clicked
